### ISSUE TITLE
Issue with two USB Alvium 1800 U -508 on Nvidia Jetson Xavier NX , vimbasrc mixing frames

### ISSUE THREAD

**Issue by iliesaya** [alliedvision/gst-vimbasrc#1]
I have a python flask web application to preview and record camera's video, I was using v4l2src with webcam before getting the Alvium 1800 U -508 usb , I need to preview and save the two camera simultaneously. 

```

camName = 'DEV_1AB22C00C5A8'

camVimbaUSb = (f"vimbasrc camera={camName} settingsfile=/home/jetson/{camConfig}.xml ! video/x-raw,format=RGB ! "
                "videoconvert ! video/x-raw ! nvvidconv ! video/x-raw(memory:NVMM) ! "
                "nvvidconv ! video/x-raw, width=616, height=514 ! " 
                "videoconvert ! video/x-raw, format=(string)BGR ! appsink")

...


thisCap = cv2.VideoCapture(camVimbaUSb, cv2.CAP_GSTREAMER)

```

the camConfig.xml has been generated by Vimba viewer, I just activated auto exposure and auto white balance. 

Here is a video of the issue : 

[https://www.youtube.com/watch?v=ZvS6HnZDQj4](https://www.youtube.com/watch?v=ZvS6HnZDQj4)

The frame from camera 1 and camera 2 get mixed up, it jump from left, to right, or both are displaying the same camera . 

Any idea ?

thanks !

EDIT : this also seems to happen when I am only displaying 1 camera but 2 are connected to the jetson's usb board ! It display sometime the frame from camera 1 and sometime the frame from camera 2 ...

**Comment by NiklasKroeger-AlliedVision** [comment]
First off: very interesting use of the element. I hadn't thought of using it as an OpenCV video capture device! Neat idea.

> The frame from camera 1 and camera 2 get mixed up, it jump from left, to right, or both are displaying the same camera .

Did this also happen when you used the `v4l2src` element? Looking at the used GStreamer pipeline I cannot see an obvious problem. I am also able to run two simple test pipelines from the command line that show images from two cameras with no mixups:

```
Terminal-1: gst-launch-1.0 vimbasrc camera=<DEVICE_ID_ONE> ! videoconvert ! autovideosink
Terminal-2: gst-launch-1.0 vimbasrc camera=<DEVICE_ID_TWO> ! videoconvert ! autovideosink
```

Is it possible that the images get mixed up somewhere between recording and visualization in your code? I understand you probably cannot share all the code with me but a minimal example showing the problem would be immensely helpful in trying to replicate it on my machine.

Generally the `vimbasrc` element communicates only with a single camera and buffers should not really be shared between multiple instances of the element. So this mixing is very surprising...

> this also seems to happen when I am only displaying 1 camera but 2 are connected to the jetson's usb board ! It display sometime the frame from camera 1 and sometime the frame from camera 2 ...

This is also very odd. As I mentioned the element only creates a connection to a single camera and communicates with that. It should not be possible to "hop around" and occasionally receive frames from one camera and occasionally from the other. It almost sounds like there is something weird happening in the device enumeration on a USB level where the device handles switch around between the connected devices....

**Comment by iliesaya** [comment]
No problem running 2 terminal with gst-launch-1.0 : 

```
gst-launch-1.0 vimbasrc camera=DEV_1AB22C00C5A9 exposureauto=2 balancewhiteauto=0 do-timestamp=false !  \
video/x-raw,format=RGB !  \
videoconvert ! video/x-raw ! nvvidconv ! 'video/x-raw(memory:NVMM)' !  \
nvvidconv ! 'video/x-raw, width=616, height=514'  !  \
xvimagesink

gst-launch-1.0 vimbasrc camera=DEV_1AB22C00C5A8 settingsfile=/home/jetson/VIMBAUSB2.xml !  \
video/x-raw,format=RGB !  \
videoconvert ! video/x-raw ! nvvidconv ! 'video/x-raw(memory:NVMM)' !  \
nvvidconv ! 'video/x-raw, width=616, height=514'  !  \
xvimagesink
```

<img width="1596" alt="Screen Shot 2021-06-29 at 17 32 58" src="https://user-images.githubusercontent.com/6323038/123816783-45d8de00-d900-11eb-8dbc-7077c5057968.png">

```
lsusb : 
path=/dev/bus/usb/002/003
    description=
    manufacturer=Allied Vision
    device=ALVIUM 1800 U-508c
    search string= Allied Vision ALVIUM 1800 U-508c
path=/dev/bus/usb/002/004
    description=
    manufacturer=Allied Vision
    device=ALVIUM 1800 U-508c
    search string= Allied Vision ALVIUM 1800 U-508c
```

EDIT2 : I did not manage to reproduce the jumping from 2 camera with only 1 is displayed, strange.

**Comment by NiklasKroeger-AlliedVision** [comment]
> No problem running 2 terminal with gst-launch-1.0 :

Well that is at least something.

The `vimbasrc` element itself works by recording images via asynchronous image acquisition and upon receiving an image placing them in a [global `GAsyncQueue` named `g_filled_frame_queue`](https://github.com/alliedvision/gst-vimbasrc/blob/376761489f3a73cb97a55b71c47aaf34d1fdedc7/src/gstvimbasrc.h#L147). With this "mixing" of frames you are seeing I am getting worried that the two instances of the `vimbasrc` element that are being created somehow share this global queue. If they are being instantiated from the same process this might be the case. I have to admit I am not sure. But this would also explain why you experience this only with the OpenCV code as they are likely sharing some resources here, but not when two separate `gst-launch-1.0` commands are executed in the terminal.

I will need to try and create something to replicate this to make sure that this is happening. But should that really turn out to be the problem I would need to perform some refactoring of the code so ensure that a separate `GAsyncQueue` is used per camera...

Thank you for bringing this to our attention!

**Comment by iliesaya** [comment]
Thanks for your support, my code is a mix of this https://blog.miguelgrinberg.com/post/flask-video-streaming-revisited and https://github.com/ultralytics/yolov3/blob/master/utils/datasets.py and became very specific to a certain task so I can't share it easyly to reproduce , but I hope these links helps

**Comment by NiklasKroeger-AlliedVision** [comment]
> I must say the whole things is very very slow, like 1 frame every 5 seconds, and with Vimba viewer I am locked to +- 10 fps , my camera should be 65fps , even when I change exposure to minimum I got 12 fps max. My jetson xavier NX have 4x USB 3.1 though ... I did increase usb fs with the command sudo sh -c 'echo 1000 > /sys/module/usbcore/parameters/usbfs_memory_mb'

Please also check the value that is set for the `DeviceLinkThroughputLimit` feature. This feature is used to reduce the amount of data sent by a camera via the USB bus to allow other devices enough free bandwidth for communication as well as some overhead. Generally running two cameras on the same USB bus also means, that each of them only has half of the usual USB bandwidth available to it.

If you feel like the cameras are generally slower than you would expect (when viewed with the Vimba Viewer, using the included examples like `AsynchronousGrab` feel free to also contact our support via [the form on our website](https://www.alliedvision.com/en/support/contact-support-and-repair.html). They have more experience in these general optimizations than I do and might be able to give some more hints on how you can improve your experience.

Additionally the `vimbasrc` element must perform a `memcpy` of the received vimba frames before they are pushed down the pipeline as the memory allocated for a vimba frame is generally reused once the frame is no longer needed (re-queued for next capture). Because GStreamer also attempts to reuse the memory of the used buffer as much as possible there is no clear way to know when it would be save to re-queue the vimba frame leading to this necessary `memcpy`. You may be able to achieve higher performance by using the Vimba API directly as this could be used to prevent this `memcpy`, but you loose the benefits of GStreamer with that.

**Comment by NiklasKroeger-AlliedVision** [comment]
Issue can also be reproduced by running the following `gst-launch` command which uses two `vimbasrc` elements each displaying to a separate `autovideosink` (`videoscale` element and corresponding scale via capsfilter is optional and only used so the windows can be seen easily side by side).

```
gst-launch-1.0 vimbasrc camera=<DEVICE_ID_ONE> ! videoscale ! video/x-raw,width=768,height=512 ! queue ! videoconvert ! autovideosink vimbasrc camera=<DEVICE_ID_TWO> ! videoscale ! video/x-raw,width=768,height=512 ! queue ! videoconvert ! autovideosink
```

This means the global filled frame queue needs to go and be replaced with a local one to prevent this mixing.

Output from `GST_DEBUG=vimbasrc:TRACE` also shows that the camera shutdown does not work cleanly in this case as shutting down the first instance of `vimbasrc` calls the Vimba API shutdown function preventing the clean shutdown of the second instance of `vimbasrc`:

```
[...]
Freeing pipeline ...
0:00:47.710233000 20932 000001EBF1B71F90 TRACE               vimbasrc gstvimbasrc.c:934:gst_vimbasrc_dispose:<vimbasrc1> dispose
0:00:47.711939000 20932 000001EBF1B71F90 TRACE               vimbasrc gstvimbasrc.c:945:gst_vimbasrc_finalize:<vimbasrc1> finalize
0:00:47.717998000 20932 000001EBF1B71F90 INFO                vimbasrc gstvimbasrc.c:952:gst_vimbasrc_finalize:<vimbasrc1> Closed camera DEV_1AB22C00041C
0:00:48.540513000 20932 000001EBF1B71F90 INFO                vimbasrc gstvimbasrc.c:965:gst_vimbasrc_finalize:<vimbasrc1> Vimba API was shut down
0:00:48.548126000 20932 000001EBF1B71F90 TRACE               vimbasrc gstvimbasrc.c:934:gst_vimbasrc_dispose:<vimbasrc0> dispose
0:00:48.553961000 20932 000001EBF1B71F90 TRACE               vimbasrc gstvimbasrc.c:945:gst_vimbasrc_finalize:<vimbasrc0> finalize
0:00:48.559943000 20932 000001EBF1B71F90 ERROR               vimbasrc gstvimbasrc.c:959:gst_vimbasrc_finalize:<vimbasrc0> Closing camera DEV_1AB22D01BBB8 failed. Got error code: API not started.
```

I will update this issue  once I have some working code for this.

**Comment by NiklasKroeger-AlliedVision** [comment]
I just created a new beta release for version 0.3.2 which includes code changes that in my tests fix the problem (no longer present with pipeline from comment above). The code can be found in the branch [issue/1](https://github.com/alliedvision/gst-vimbasrc/tree/issues/1) and built versions of the element can be found in [the corresponding beta release on the releases page](https://github.com/alliedvision/gst-vimbasrc/releases/tag/v0.3.2-beta1). Please let me know if this fixes your problem.

**Comment by PazAranyi** [comment]
> 

I tried to use the beta version, but I have the same problem mentioned below.
When I try to use two Allvium cameras simultaneously, one isn't working.
Do you have any suggestions on how to run two pipelines with Vimbasrc simultaneously?

**Comment by NiklasKroeger-AlliedVision** [comment]
@PazAranyi could you please provide some more information on your setup and what exactly you attempted
- gstreamer pipeline you tried to launch
- Error messages encountered. Ideally attach a log file. You can enable log messages for the gst-vimbasrc element by setting the environment variable `GST_DEBUG=vimbasrc:DEBUG` before launching your gstreamer application
- What system are you using (original question was using the Xavier NX, are you using that as well or a different system?
- What camera models are you using (exact model number would be great)?
- Short description of the hardware setup (i.e. how are the cameras connected)

In the meantime: Are you able to open both cameras in the VimbaViewer and stream them at the same time? With USB cameras it is for example possible, that the bandwidth on a low-power board like the NX is not enough to support stable streams for two cameras if they both require high bandwidths. In that case the cameras need to be configured to share the available bandwidth in a fair way.

In case you do not have a display attached to the system you can also try streaming frames from them with the `AsynchronousGrab` example in the VimbaC directory of your Vimba installation. On Linux you find pre-compiled binaries of the examples in `<Path-where-Vimba-was-unpacked-to>/VimbaC/Examples/Bin/<architecture-dependent-directory>/`
With the `ListCameras` example you will see the connected cameras and their corresponding IDs. These IDs can be used as parameter to `AsynchronousGrab` to start a stream from that camera. Adding the parameter `/i` to the call of `AsynchronousGrab` you will get some extra information regarding the frame transmission, including if the frame transfer was complete or incomplete.

Example from my system:
```
$ ListCameras
[...]
Vimba Version Major: 1 Minor: 9 Patch: 0
Cameras found: 2

/// Camera Name: Allied Vision 1800 U-500m
/// Model Name: 1800 U-500m
/// Camera ID: <DEV_ID-OF-CAMERA-1>
[..]

/// Camera Name: Allied Vision 1800 U-500m
/// Model Name: 1800 U-500m
/// Camera ID: <DEV_ID-OF-CAMERA-2>
[...]
```
Then I started two terminals where I ran the following commands simultaneously:
```
# Terminal 1
$ AsynchronousGrab /i DEV_1AB22C00041C
Vimba Version Major: 1 Minor: 9 Patch: 0
Opening camera with ID: <DEV_ID-OF-CAMERA-1>
Press <enter> to stop acquisition...
Frame ID:0 Status:Complete Size:2592x1944 Format:0x01080001 FPS:?
Frame ID:1 Status:Complete Size:2592x1944 Format:0x01080001 FPS:38.61
Frame ID:2 Status:Complete Size:2592x1944 Format:0x01080001 FPS:38.49
[...]

==================================================
# Terminal 2
$ AsynchronousGrab /i <DEV_ID-OF-CAMERA-2>
Vimba Version Major: 1 Minor: 9 Patch: 0
Opening camera with ID: <DEV_ID-OF-CAMERA-2>
Press <enter> to stop acquisition...
Frame ID:0 Status:Complete Size:2592x1944 Format:0x01080001 FPS:?
Frame ID:1 Status:Complete Size:2592x1944 Format:0x01080001 FPS:38.66
Frame ID:2 Status:Complete Size:2592x1944 Format:0x01080001 FPS:38.55
Frame ID:3 Status:Complete Size:2592x1944 Format:0x01080001 FPS:38.73
[...]
```

For me the frames received from both cameras showed the status `Complete`. If your results show `Incomplete` frames, this is a likely cause of your problem and you would need to adjust camera settings to get a stable stream with multiple cameras on your system. That is a more general camera issue and not directly related to gst-vimbasrc. If you require assistance in getting multiple cameras to stream in the VimbaViewer or with the AsynchronousGrab example I would suggest you also contact our support via [the form on our website](https://www.alliedvision.com/en/support/contact-support-and-repair.html).

**Comment by PazAranyi** [comment]
Thank you for your fast reply.

- gstreamer pipeline you tried to launch - I tried multiple pipelines to autovideosink and filesink, such as:

"gst-launch-1.0 vimbasrc camera=DEV_1AB22C00BC01 ! video/x-raw,format=RGB ! videorate ! videoconvert ! queue ! autovideosink"

and
"gst-launch-1.0 vimbasrc camera=DEV_1AB22C010CEC settingsfile=/home/paz/C01_1.xml  ! video/x-raw,format=RGB ! videorate ! videoconvert ! queue ! jpegenc  ! avimux ! filesink location=alvi_2.avi"

- Error messages encountered - When I start the second camera, the first terminal sends:
"
0:00:22.195563128 164942 0x55601ae57180 WARN                vimbasrc gstvimbasrc.c:1272:gst_vimbasrc_create:<vimbasrc0> Received frame with ID "114" was incomplete
0:00:22.195576862 164942 0x55601ae57180 DEBUG               vimbasrc gstvimbasrc.c:1283:gst_vimbasrc_create:<vimbasrc0> Dropping incomplete frame and requeueing buffer to capture queue
"

- What system are you using - HP ZBOOK Power G8 (i7 11800H)


- What camera models are you using - Alvium 1800 U-1240 and Alvium 1800 U-1242 


- Short description of the hardware setup - Directly to the USB type A slots.


I tried to use both of them from the Viewer, and it failed (only the first cam worked). But I can run Alvium and IDS cameras simultaneously on the same machine when I use Aravis or IDS peak and Vimba. So I'm not sure it is a bandwidth or power problem.

I will try to run the AsynchronousGrab example and see if it helps.

**Comment by NiklasKroeger-AlliedVision** [comment]
Both of the pipelines you showed only start streams with a single camera each. Not two streams from the same gst-launch process. This is a difference from the original question. 

```
0:00:22.195563128 164942 0x55601ae57180 WARN vimbasrc gstvimbasrc.c:1272:gst_vimbasrc_create: Received frame with ID "114" was incomplete
0:00:22.195576862 164942 0x55601ae57180 DEBUG vimbasrc gstvimbasrc.c:1283:gst_vimbasrc_create: Dropping incomplete frame and requeueing buffer to capture queue
```
This indicates, that a single frame (in this case the frame with ID 114) was incomplete and therefore dropped. Occasional incomplete frames may come up if transmission is interrupted by something and is for USB devices unfortunately something that can happen. Other attached USB devices might interrupt the transfer leading to problems like this. If you see a lot of these messages it is a clear indication, that the USB bandwidth needs to be managed better.

> I tried to use both of them from the Viewer, and it failed (only the first cam worked).
> [...]
> I tried to run the AsynchronousGrab example, showing "Incomplete" on the second camera.

To me this sounds like it points to a problem with the USB bandwidth. The first setting you could take a look at for each camera is the `DeviceLinkThroughputLimit`. The easiest way to play around with that is with the VimbaViewer. Try reducing the value in both cameras far enough that you get a stable stream. If your cameras are colour cameras, you might also consider recording frames from them in a Bayer format and debayering the image on the host. This requires additional processing power on the host machine, but reduces the amount of pixel data that need to be transferred from the camera to the host and might improve your experience.

Since this is however a general camera issue and not really related to gst-vimbasrc, I would suggest that you contact our support via [the form on our website](https://www.alliedvision.com/en/support/contact-support-and-repair.html). They are much more experienced in troubleshooting streaming setups than I am and will probably have better ideas on how you can stabilize your stream.
