### ISSUE TITLE
ProsilicaGT 1380s Does Not Connect Through Vimba Viewer

### ISSUE THREAD

**Issue by dkerr523** [alliedvision/gst-vimbasrc#15]
We are using ProsilicaGT 1380 cameras and have started up Vimba Viewer which detects the cameras that are connected to the NIC.  We try to connect by selecting Action > Open Camera By IP.  The error below is shown.  Also, we cannot open any of the cameras in anything other than configuration mode.  Not sure what to do now...

![image](https://user-images.githubusercontent.com/122304525/211372965-795dbe61-e3fe-4833-8d5a-a2f7dc8d8115.png)

**Comment by BernardoLuck** [comment]
Hello, 

I propose to move this issue to the official support from Allied Vision. Please, write an Email to support@alliedvision.com, explaining in detail the issue. Can you also described in your email the Hardware used? Are you using a dedicated Network card(which one), a Switch and  high quality ethernet Cables? 
BR

**Comment by dkerr523** [comment]
Thanks for the response.  We did hear back from Allied Vision support after a week's wait.  It turns out that all devices, NICs and cameras must be on the same subnet.  Suggest updating documentation to specifically point this out in the troubleshooting section.
