### ISSUE TITLE
Reduce CPU usage - DMA and ZeroCopy

### ISSUE THREAD

**Issue by VLongobardi** [alliedvision/gst-vimbasrc#24]
Hi all, 
Do you know if there is a way to speed up the frame acquisition process, for instance using DMA and zero-copy mechanism?

**Comment by BernardoLuck** [comment]
Hello VLongobardi, 

the VimbaAPI does not provide any acquisition mechanis with DMA or zero-copy. For a deeper discussion in this topic I would suggest to open a support ticket from the following link: 

https://www.alliedvision.com/en/about-us/contact-us/technical-support-repair-/-rma/
